//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_side.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public int CID { get; set; }
        public string Email { get; set; }
        public string subject { get; set; }
        public string Message { get; set; }
    }
}
