//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_side.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class tbladmin
    {
        
        [Required(ErrorMessage = "USERNAME REQUIRED")]
        public string AdminName { get; set; }
        [Required(ErrorMessage = "INVALID PASSWORD")]
        public string Password { get; set; }
    }
}
