//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_side.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustDetail_Cart
    {
        public int CartID { get; set; }
        public Nullable<int> UID { get; set; }
        public Nullable<int> CID { get; set; }
        public Nullable<int> Qty { get; set; }
    
        public virtual tbl_costumerdetails tbl_costumerdetails { get; set; }
        public virtual tblCategoryDetail tblCategoryDetail { get; set; }
    }
}
