//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Web;
namespace Admin_side.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class tblCategoryDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCategoryDetail()
        {
            this.tblCustDetail_Cart = new HashSet<tblCustDetail_Cart>();
            this.tblorders = new HashSet<tblorder>();
        }
    
        public int CID { get; set; }
        public Nullable<int> PID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Qty { get; set; }
        public string ProductDescription { get; set; }
        [DisplayName("Upload Image")]
        public string ImageUrl { get; set; }

        public HttpPostedFileBase Imagefile { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual tblProductDetail tblProductDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCustDetail_Cart> tblCustDetail_Cart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblorder> tblorders { get; set; }
    }
}
