//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_side.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPayment_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPayment_Details()
        {
            this.tblorders = new HashSet<tblorder>();
        }
    
        public int PaymentID { get; set; }
        public string Name { get; set; }
        public Nullable<long> AccNumber { get; set; }
        public string BankName { get; set; }
        public string Mode { get; set; }
        public Nullable<int> CvvNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblorder> tblorders { get; set; }
    }
}
